version: '3.8'
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:arm64v8-latest
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - /mnt/Media:/media
      - ./data/jellyfin:/config
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:arm64v8-latest
    container_name: radarr
    ports:
      - "7878:7878"
    volumes:
      - /mnt/Media:/media
      - ./data/radarr:/config
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:arm64v8-latest
    container_name: sonarr
    ports:
      - "8989:8989"
    volumes:
      - /mnt/Media:/media
      - ./data/sonarr:/config
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:arm64v8-latest
    container_name: overseerr
    ports:
      - "5055:5055"
    volumes:
      - ./data/overseerr:/config
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:arm64v8-latest
    container_name: qbittorrent
    ports:
      - "8080:8080"
    environment:
      - WEBUI_PORT=8080
    volumes:
      - /mnt/Media:/media
      - ./data/qbittorrent:/config
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:arm64v8-latest
    container_name: bazarr
    ports:
      - "6767:6767"
    volumes:
      - /mnt/Media:/media
      - ./data/bazarr:/config
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:arm64v8-latest
    container_name: jackett
    ports:
      - "9117:9117"
    volumes:
      - ./data/jackett:/config
    restart: unless-stopped
