version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: bridge
    ports:
      - 8096:8096
    volumes:
      - /mnt/Media/movies:/media/movies
      - /mnt/Media/tv:/media/tv
      - /mnt/Media/downloads:/media/downloads
      - ~/docker-configs/jellyfin/config:/config
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: bridge
    ports:
      - 7878:7878
    volumes:
      - /mnt/Media/movies:/movies
      - /mnt/Media/downloads:/downloads
      - ~/docker-configs/radarr/config:/config
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: bridge
    ports:
      - 8989:8989
    volumes:
      - /mnt/Media/tv:/tv
      - /mnt/Media/downloads:/downloads
      - ~/docker-configs/sonarr/config:/config
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    network_mode: bridge
    ports:
      - 5055:5055
    volumes:
      - ~/docker-configs/overseerr/config:/app/config
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Bratislava
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    network_mode: bridge
    ports:
      - 6767:6767
    volumes:
      - /mnt/Media/movies:/movies
      - /mnt/Media/tv:/tv
      - ~/docker-configs/bazarr/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    network_mode: bridge
    ports:
      - 9117:9117
    volumes:
      - ~/docker-configs/jackett/config:/config
      - /mnt/Media/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    restart: unless-stopped
